name: yaka_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/ad_categories/
    - assets/payment/
    - assets/products/
    - assets/categories/
